name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone repo
      - uses: actions/checkout@v3

      # Step 2: Optional - validate JS files with a linter (if you set one up)
      # - name: Lint JS
      #   run: |
      #     npm install -g eslint
      #     eslint .

      # Step 3: Minimal step to pass the workflow
      - name: Workflow sanity check
        run: echo "Build successful - vanilla JS library"
